<?php $this->headScript()->captureStart() ?>
$(document).ready(function(){
    $('.collapsible').collapsible();
  });
<?php $this->headScript()->captureEnd() ?>

<ul class="collapsible">
    <?php foreach ($items as $item) : ?>
    <li>
        <div class="collapsible-header">
            <i class="material-icons"><?= $item->getIcon() ?></i>
            <?= $item->getHeadline() ?>
        </div>
        <div class="collapsible-body">
            <span><?= $item->getContent() ?></span>
        </div>
    </li>
    <?php endforeach; ?>
</ul>
        